services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: gunicorn example_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - .:/app
      - static_volume:/var/www/example_project/staticfiles  # Host path for static files
      - db_volume:/app/db.sqlite3
    expose:
      - "8000"  # Exposes port 8000 to other Docker services
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  internal_nginx:
    image: nginx:latest
    container_name: internal_nginx
    volumes:
      - ./internal_nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/example_project/staticfiles  # Shared static files
    ports:
      - "8081:80"  # Maps host port 8081 to container port 80
    expose:
      - "80"  # Exposes port 80 to other Docker services
    depends_on:
      - web
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/example_project/staticfiles  # Ensure this path exists on the host
  db_volume:
    # Define your database volume settings here
